name: oppy2_frontend
description: "Backend para práctica de inglés con IA - Enfoque Autenticación"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- Iconos ---
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0
  google_sign_in: ^6.2.1

  # --- Comunicación con Backend ---
  dio: ^5.4.1                # El 'requests' de Flutter, más potente y con interceptores
  
  # --- Seguridad ---
  flutter_secure_storage: ^9.0.0 # Guarda los JWT en el Keystore/Keychain del celular
  
  # --- Gestión de Estado ---
  provider: ^6.1.2           # Para que toda la app sepa si el usuario está logueado
  app_links: ^7.0.0
  flutter_riverpod: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/bigben.jpg